[package]
name = "bifrost-common-node"
version = "1.0.0"
description = "The common code shared between node specifications for BIFROST Node"
authors = ["bifrost-platform"]
homepage = "https://thebifrost.io"
edition = "2021"
license = "Unlicense"
repository = "https://github.com/bifrost-platform/bifrost-node"

[dependencies]
# third-party dependencies
jsonrpc-core = "18.0.0"
futures = { version = "0.3" }

# substrate client dependencies
sc-client-api = { git = "https://github.com/bifrost-platform/substrate", branch = "thebifrost-legacy-v1.1.4" }
sc-rpc = { git = "https://github.com/bifrost-platform/substrate", branch = "thebifrost-legacy-v1.1.4" }
sc-rpc-api = { git = "https://github.com/bifrost-platform/substrate", branch = "thebifrost-legacy-v1.1.4" }
sc-transaction-pool = { git = "https://github.com/bifrost-platform/substrate", branch = "thebifrost-legacy-v1.1.4" }
sc-chain-spec = { git = "https://github.com/bifrost-platform/substrate", branch = "thebifrost-legacy-v1.1.4" }
sc-consensus-manual-seal = { git = "https://github.com/bifrost-platform/substrate", branch = "thebifrost-legacy-v1.1.4" }
sc-finality-grandpa = { git = "https://github.com/bifrost-platform/substrate", branch = "thebifrost-legacy-v1.1.4" }
sc-finality-grandpa-rpc = { git = "https://github.com/bifrost-platform/substrate", branch = "thebifrost-legacy-v1.1.4" }
sc-network = { git = "https://github.com/bifrost-platform/substrate", branch = "thebifrost-legacy-v1.1.4" }
sc-service = { git = "https://github.com/bifrost-platform/substrate", branch = "thebifrost-legacy-v1.1.4", features = ["wasmtime"] }

# substrate primitives dependencies
sp-runtime = { git = "https://github.com/bifrost-platform/substrate", branch = "thebifrost-legacy-v1.1.4" }
sp-api = { git = "https://github.com/bifrost-platform/substrate", branch = "thebifrost-legacy-v1.1.4" }
sp-blockchain = { git = "https://github.com/bifrost-platform/substrate", branch = "thebifrost-legacy-v1.1.4" }

# Frontier dependencies
fc-db = { default-features = false, git = "https://github.com/bifrost-platform/frontier", branch = "thebifrost-legacy-v1.1.4" }
fc-rpc = { default-features = false, git = "https://github.com/bifrost-platform/frontier", branch = "thebifrost-legacy-v1.1.4", features = ["rpc_binary_search_estimate"] }
fc-rpc-core = { default-features = false, git = "https://github.com/bifrost-platform/frontier", branch = "thebifrost-legacy-v1.1.4" }
fp-rpc-debug = { default-features = false, git = "https://github.com/bifrost-platform/frontier", branch = "thebifrost-legacy-v1.1.4" }
fp-storage = { default-features = false, git = "https://github.com/bifrost-platform/frontier", branch = "thebifrost-legacy-v1.1.4" }
fp-rpc = { default-features = false, git = "https://github.com/bifrost-platform/frontier", branch = "thebifrost-legacy-v1.1.4" }

# Local Dependencies
bp-core = { path = "../../primitives/core" }

[features]
default = []
runtime-benchmarks = []
